version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: google_ads_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: google_ads_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql 